[package]
name = "monoio-http-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
http = "0.2.9"
monoio = "0.1.9"
monoio-http = "0.2.3"
monoio-http-client = "0.2.5"
